camunda/zeebe-benchmark-helm

zeebe-benchmark/values.yaml
We reduced recently the resources and workload of the benchmarks, but not the disk sizes. This PR reduces the disk size by 1/4. The disk size for Zeebe is now similar to the cluster plan G3-S, and it is still serving a similar workload. The elasticsearch is a bit higher then for G3-S, since we have no auto resizing and we need a bit bigger disk for our workload.
This should help to reduce further our costs of running benchmarks since right now [disk are a main factor in our costs.](https://console.cloud.google.com/billing/01704C-DE13F5-D69A2F/reports;chartType=STACKED_BAR;timeRange=LAST_30_DAYS;grouping=GROUP_BY_SKU;projects=zeebe-io?project=zeebe-io&organizationId=252201914815)
----
Details:
| | New Disk sizes | Weekly | Comment
|-|----------------------|------------|----------|
| …
=> Reduce disk sizes

profiling.yaml
Using the busybox wget was a bad idea because there's no TLS verification and connections can fail when there are multiple handshakes involved: https://github.com/docker-library/busybox/issues/134
Here we switch to alpine which should not have issues downloading pyroscope over TLS.
=> fix: download pyroscope from alpine container for TLS verification

charts/zeebe-benchmark/values.yaml
With the recent changes, our old throughput target of 75 PI/s wasn't stressing the system anymore:
A recent run of main targeting 150PI/s results in ~130PI/s and decent backpressure:
=> Increase throughput target to 150 PI/s

charts/zeebe-benchmark/templates/zeebe-config.yaml, charts/zeebe-benchmark/values.yaml
Allows 
```shell
helm install os-test-cfg ./charts/zeebe-benchmark --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=16
```
Results in a mounted config map like 
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: zeebe-config
labels:
helm.sh/chart: zeebe-benchmark-0.1.3
app.kubernetes.io/name: zeebe-benchmark
app.kubernetes.io/instance: os-test-cfg
app.kubernetes.io/version: "8.1.2"
app.kubernetes.io/managed-by: Helm
data: 
application.yml: | 
zeebe:
broker:
experimental:
maxAppendsPerFollower: 16
```
This overwrites the default application.yml which hopefully only contains default values.
=> feat: set zeebe config via values

charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/worker.yaml
Once we start using worker and starter built by jib, `JAVA_OPTIONS` won't apply. Instead, we [can and should](https://stackoverflow.com/questions/52986487/what-is-the-difference-between-jdk-java-options-and-java-tool-options-when-using) use `JDK_JAVA_OPTIONS`
=> fix: use native env vars to set worker and starter properties

charts/zeebe-benchmark/values.yaml
The zeebe-config ConfigMap currently only has a `java-opts` field when profiling is enabled. Marking this as optional allows the  benchmark to start when profiling is not explicitly enabled.
=> fix: don't fail if no javaOpts are provided

charts/zeebe-benchmark/templates/NOTES.txt
Notes are printed when the chart is installed, which should help the user to understand what has been installed and how to use it.
closes #22 
**Example:**
```
$ helm install xzy charts/zeebe-benchmark --dry-run --set zeebe.profiling.enabled=true
...
NOTES:
Installed Zeebe cluster with:
* 3 Brokers
* 2 Gateways
The benchmark is running with:
* Starter replicas=1
* Worker replicas=3
* Publisher replicas=0
* Timer replicas=0
Profiling enabled. Access pyroscope via port-forwarding:
kubectl -n pyroscope port-forward svc/pyroscope 4040
```
=> feat: enhance release notes

charts/zeebe-benchmark/templates/publisher.yaml, charts/zeebe-benchmark/templates/timer.yaml, charts/zeebe-benchmark/test/golden/publisher.golden.yaml, charts/zeebe-benchmark/test/golden/timer.golden.yaml, charts/zeebe-benchmark/test/golden_test.go, charts/zeebe-benchmark/test/zeebe_config_test.go
Use correct JDK_JAVA_OPTIONS instead of outdated JAVA_OPTIONS which causes https://github.com/camunda/zeebe/issues/11845
+ Remove concurrency in tests to make sure that tests are not fighting each other.
=> Fix app configs

charts/zeebe-benchmark/templates/publisher.yaml, charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/timer.yaml, charts/zeebe-benchmark/templates/worker.yaml, charts/zeebe-benchmark/test/golden/publisher.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/test/golden/timer.golden.yaml, charts/zeebe-benchmark/test/golden/worker.golden.yaml
In order to export prometheus metrics we need to expose the right container port.
closes https://github.com/camunda/zeebe/issues/11988
------
Example for worker pod:
```
sum(rate(grpc_client_completed_total{namespace=~"$namespace"}[1m])) by (grpc_method, grpc_code)
```
=> feat: expose metrics port

charts/zeebe-benchmark/templates/leader-balancing-cron.yaml, charts/zeebe-benchmark/test/golden/leader-balancing-cron.golden.yaml
By upgrading Spring Boot to version 3.x in Zeebe, the management endpoints will fail with a 404 when having a trailing slash, for example: `/actuator/rebalance/` (see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes). This PR removes the trailing slashes when calling the rebalancing endpoint.
related to https://github.com/camunda/zeebe/pull/11103
=> fix: remove trailing slash to rebalance leaders

charts/zeebe-benchmark/templates/clients-service.yaml, charts/zeebe-benchmark/templates/clients-service.yml, charts/zeebe-benchmark/templates/publisher.yaml, charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/timer.yaml, charts/zeebe-benchmark/templates/worker.yaml, charts/zeebe-benchmark/test/golden/clients-service.golden.yaml, charts/zeebe-benchmark/test/golden/publisher.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/test/golden/timer.golden.yaml, charts/zeebe-benchmark/test/golden/worker.golden.yaml, charts/zeebe-benchmark/test/golden_test.go, charts/zeebe-benchmark/values.yaml
Migrates back from Google Managed Prometheus setup to the standard Prometheus service monitor. Our set up uses the label `release: monitoring` to grab service monitors.
Additionally adds a new template, `client-service.yml`, which adds a headless service and monitor to grab all client deployments. This works by adding a new label, `zeebe.io/component: client` to all of our clients.
If you know of a better label to use for the clients, let me know.
=> refactor: migrate to standard Prometheus service monitor

charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/worker.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/test/golden/worker.golden.yaml, charts/zeebe-benchmark/values.yaml
This PR disables integration of benchmarks with Google Managed Prometheus, as we've now migrated to a self-managed stack.
=> refactor: disable GMP integration via labels

charts/zeebe-benchmark/values.yaml
Old curator image has been renamed by bitnami, to elasticsearch-curator-archived
See https://medium.com/@zelldon91/looks-like-bitnami-elasticsearch-curator-is-gone-db1fa2260a97
=> fix: use renamed curator image

charts/zeebe-benchmark/values.yaml
Needed to let zeebe run with the `zeebe` user as it otherwise lacks permissions on mounts. 
relates to https://github.com/camunda/zeebe/issues/12382
=> fix: set fsGroup for zeebe user

Makefile, charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/test/golden/deployment.golden.yaml, charts/zeebe-benchmark/test/golden/servicemonitor.golden.yaml, charts/zeebe-benchmark/test/golden_camunda_platform_test.go, charts/zeebe-benchmark/test/golden_elastic_exporter_test.go, charts/zeebe-benchmark/values.yaml
In order to support Operate in our benchmarks we want to also add the elasticsearch metric exporter to our benchmarks.
Related project https://app.slack.com/client/T0PM0P1SA/C05GGP8C214
Since it is also interesting to see how elasticsearch behaves without Operate I want to enable it by default.
This PR adds https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter as dependency and sets the right properties, like servicemonitor and connection URL. 
Furthermore, we add some golden tests to verify that the resources are added and deployed with right configs.
--------
Example deployment https://grafana.dev.zeebe.io/d/elasticsearch/elasticsearch?orgId=1&var-server=Prometheus&var-cluster=All&var-namespace=ck-helm-test&var-index=All&from=now-15m&to=no …
=> Add elastic metric exporter

charts/zeebe-benchmark/test/golden/c8-curator-configmap.golden.yaml, charts/zeebe-benchmark/values.yaml
Sets the maximum index size back to one, such that we delete indices early. We need to reconfigure this when we enable operate, but this can be done separately for that specific benchmark.
=> fix: set index size to 1

charts/zeebe-benchmark/README.md, charts/zeebe-benchmark/templates/curator-configmap.yaml, charts/zeebe-benchmark/templates/curator-cronjob.yaml, charts/zeebe-benchmark/test/golden/curator-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/curator-cronjob.golden.yaml, charts/zeebe-benchmark/test/golden_test.go, charts/zeebe-benchmark/values.yaml
Adds a new retention policy to the helm chart which allows to configure indice deletion on a more fine granular level.
It is per default disabled, since we will use in our normal benchmarks the old approach. But if we need it we can enable it, in the operate benchmarks for example and disable the old (which comes from the parent chart)
With the new retention policy we can define policy for each specific index name or for a certain pattern, etc.
=> More fine granular retention policy

charts/zeebe-benchmark/templates/curator-cronjob.yaml, charts/zeebe-benchmark/test/golden/curator-cronjob.golden.yaml
We use  a custom config map and not the generic camunda-platform one. Without this fix, the curator fails to run because it can't find the configmap.
Closes #100
=> fix: refer to custom curator config map

charts/zeebe-benchmark/test/golden/operate-configmap.golden.yaml, charts/zeebe-benchmark/values.yaml
In benchmarks with Operate, the majority of logs were coming from Operate, this should greatly reduce the costs for it.
Will become obsolete once https://github.com/camunda/camunda-platform-helm/pull/1092 is merged but we may still keep a default config in the values of the benchmark chart.
=> improve(operate): reduce log level to INFO

charts/zeebe-benchmark/values.yaml
closes [#15000](https://github.com/camunda/zeebe/issues/15000)
=> improve(gateway): increased memory to cover for push spikes

charts/zeebe-benchmark/values.yaml
We recently updated to the Camunda Platform 9.x chart, which uses now a different ES chart ([bitnami](https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch))
Our recent benchmark setup for this week (CW 04) failed because ES was not installed properly. 
The statefulset failed with:
```
Warning  FailedCreate  55s (x138 over 33h)  statefulset-controller  create Pod medic-y-2024-cw-04-0778ec7-benchmark-elasticsearch-master-0 in StatefulSet medic-y-2024-cw-04-0778ec7-benchmark-elasticsearch-master failed error: Pod "medic-y-2024-cw-04-0778ec7-benchmark-elasticsearch-master-0" is invalid: metadata.labels: Invalid value: "medic-y-2024-cw-04-0778ec7-benchmark-elasticsearch-master-586689ff7": must be no more than 63 characters
```
The problem is that the stateful set controller is …
=> Reduce elastic master name

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp, charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/README.md
The repository camunda/zeebe will be renamed to camunda/camunda, this PR adjusts all references to this repository.
> **WHY**
> The name of this repository will be changed to align better with its new role as a monorepo containing multiple products of the stack.
> https://github.com/camunda/zeebe/issues/18206
I renamed all occurrences of github.com/camunda/zeebe. I didn't do this for camunda/zeebe as this will change occurrences for docker images (which we do not plan to change yet).
For posterity, the following script has been used.
```sh
#!/bin/bash
set -euox pipefail
path=$1
find "$path" -type f -exec sed -i -E 's|github.com/camunda/zeebe([/#])?|github.com/camunda/camunda\1|g' {} \;
count=$(git -C "$path" status | grep modified -c)
echo "$count files have been updated."
if ag …
```
=> Rename camunda/zeebe repo

charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/test/golden/c8-operate-service-monitor.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-gateway-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-gateway-deployment.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-statefulset.golden.yaml, charts/zeebe-benchmark/test/golden/operate-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/operate-deployment.golden.yaml, charts/zeebe-benchmark/test/golden/operate-service.golden.yaml
The version we used before was always lagging behind, and the last released minor. This doesn't work with recent changes we did with the mono-repo and in general that we want to test in our benchmarks. 
For example, previous benchmarks failed, due to wrong configs in the old Helm chart version, as the Operate configuration has changed with the mono repo, see investigation [here](https://github.com/camunda/camunda/issues/21033#issuecomment-2288476572) 
See related discussion also [here](https://github.com/camunda/camunda-platform-helm/pull/2223#issuecomment-2289157601) 
closes https://github.com/camunda/camunda/issues/21033
=> Migrate to alpha charts

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/values.yaml
This PR enables write rate limits for benchmarks so that we can visualize flow control metrics in benchmarks.
The limit was set as 4000, as its higher than the maximum processed rate observed in benchmarks, while still being close to this value. [See discussion.](https://github.com/camunda/camunda/issues/21324)
Relates https://github.com/camunda/camunda/issues/21324
=> Enable write rate limits for the benchmarks.

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp, charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/RELEASE-NOTES.md
=> Release Zeebe Benchmark Helm Chart v0.3.0

charts/zeebe-benchmark/values-realistic-benchmark.yaml
Previously job type dispute_process_request_proof_from_vendor was shared by two tasks, this has been split up now.
Related to https://github.com/camunda/camunda/pull/22354
=> Use different worker job types

charts/zeebe-benchmark/test/golden/workers.golden.yaml, charts/zeebe-benchmark/values.yaml
Previously we had a default of 50ms instead of 300ms, increasing the delay was causing to decrease in expected throughput.
Slack thread https://camunda.slack.com/archives/C037RS2JHB8/p1726581128553019
=> fix: use previously completionDelay default

charts/zeebe-benchmark/values-realistic-benchmark.yaml
Improve the worker configuration (benchmark results see [here](https://github.com/camunda/camunda/pull/22411#issuecomment-2357619085))
1. Most of the workers have a completion delay of 300ms, and per default 10 threads.
This means per second they are able to complete ~30 in one second. As
the timeout is calculated based on the completion delay (times 6 = 1800 ms). We
have a high chance that jobs time out until we reach them.
*  Reducing the capacity should remove this risk or reduce the chance.
2. Scale down workers. To reduce load on the cluster and smooth out the throughput and reduce failures, especially job time outs we have to reduce the worker pods. Proved in a benchmark see https://github.com/camunda/camunda/pull/22411#issuecomment-2357619085
=> Improve worker configs

charts/zeebe-benchmark/templates/_helpers.tpl, charts/zeebe-benchmark/templates/credentials.yaml, charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/workers.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-credentials.golden.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-starter.golden.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-workers.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-starter.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-workers.golden.yaml, charts/zeebe-benchmark/test/saas_configuration_test.go, charts/zeebe-benchmark/values.yaml
Previously it was not possible to use the benchmark helm charts to run benchmarks against our SaaS offering. The only option was to use the starter, worker resource definitions in the mono-repo [here](https://github.com/camunda/camunda/tree/main/zeebe/benchmarks/setup/cloud-default)
This PR introduces the option to configure credentials either direct via values or reference an existing secret, which might be deployed similar as [this](https://raw.githubusercontent.com/camunda/camunda/main/zeebe/benchmarks/setup/cloud-default/cloudcredentials.yaml).
When the new Saas option is enabled workers and starter are configured to use the related credentials, and connect to a SaaS cluster via TLS.
With this we are able to support benchmarks against SaaS more easily, with the full power and …
=> Introduce SaaS support for benchmarks

CONTRIBUTING.md, charts/zeebe-benchmark/templates/workers.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-workers.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-workers.golden.yaml, charts/zeebe-benchmark/test/golden/workers.golden.yaml
With the previous worker version if we set the completion deplay, it would add both of them as seen on the medic [benchmark  of week 39](https://camunda.slack.com/archives/C05DH1F5TAR/p1727278288428469?thread_ts=1727254928.222029&cid=C05DH1F5TAR), and possibly pick the last read value which caused some issues and confusion. This way we only add the completion delay if not set.
=> Remove worker's repeated completion delay, and only add this if not set.

charts/zeebe-benchmark/test/golden/c8-zeebe-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
As we saw in https://github.com/camunda/camunda/issues/21758, a 32 GiB disk is slightly too small for our default workload.
=> fix: use larger disks to avoid throttling

charts/zeebe-benchmark/templates/workers.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-workers.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-workers.golden.yaml, charts/zeebe-benchmark/test/golden/workers.golden.yaml, charts/zeebe-benchmark/values-realistic-benchmark.yaml, charts/zeebe-benchmark/values.yaml
Our realistic benchmarks had some issues with keeping up with the load (when using the realistic payload). Job completions where lower than creations, causing a slow increase of state.
Reported also in slack https://camunda.slack.com/archives/C037RS2JHB8/p1730111585816089
Jobs seem to be not completed fast enough, but there seem to be enough in buffer
Looking into Operate of one of these benchmarks we can clearly see that we have many instances left.
Look at the process we see where most token stay.
After fixing the first part it went stuck in the refund job (so we had to adjust configs for both).
After fixing the benchmark I have run a benchmark over night. We can see that the completion and creation is the same. Even for the Process Instances! This means we will not have any left overs …
=> Fix realistic benchmark

charts/zeebe-benchmark/values-realistic-benchmark.yaml
With the previous limit throttling was very high (even > 80%). 
With this limit, there is less backpressure & less timeouts which reduce the cpu usage to around 1 (from 1.2).
For reference this is the benchmark run:
[Grafana](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730815673277&to=1730821316682&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-batch-size-32&var-pod=All&var-partition=All)
You can clearly see the difference in throttling & cpu usage before & after the restart
=> fix: increase cpu zeebe limit to 1.7 while keeping cpu-request at 1.35

charts/zeebe-benchmark/test/golden/c8-zeebe-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
Change the cpu limits in the default benchmark to match the limits  in the realistic one
=> fix: increase zeebe cpu limit to 1.7 in default benchmark

charts/zeebe-benchmark/test/golden/c8-zeebe-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
cpu requests & limits were inverted by mistake
=> fix: cpu request & limits were inverted in default benchmark

charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-gateway-deployment.golden.yaml, charts/zeebe-benchmark/test/golden/c8-zeebe-statefulset.golden.yaml, charts/zeebe-benchmark/test/golden/operate-deployment.golden.yaml, charts/zeebe-benchmark/values-realistic-benchmark.yaml
To have an early integration of the new planned Camunda Exporter with the Zeebe system and other components, update the benchmark helm charts to alpha1 and disable importer (to validate this works without importers).
=> Enable Camunda Exporter in benchmarks and disable importer in realistic benchmarks

charts/zeebe-benchmark/values.yaml
Increases the disk size from 16 to 32GB in ES.
This commit was separated from https://github.com/zeebe-io/benchmark-helm/pull/213 due to urgency of increasing the resources.
=> Increase ES disk size for the benchmarks.

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/values.yaml
This PR enables throttling in the flow control which adds more time to react and fix benchmarks before they go unhealthy.
=> Enable flow control throttling in normal benchmarks.

charts/zeebe-benchmark/test/golden/golden-credentials-starter.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-starter.golden.yaml, charts/zeebe-benchmark/test/golden/starter-extended.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/values.yaml
To address the problem with the normal benchmarks that ES disk fills to quickly which leads to backlog of unexporterd records and subsequently to fill the zeebe disk and make the partition unhealthy, this PR increases the ES disk size from 64G to 128G and reduces the PI starting rate from 150 to 60.
This is related to the changes in the exporter, as ES is filling much faster https://camunda.slack.com/archives/C05DH1F5TAR/p1736863726613569 .
Hopefully, the reducing of the PI/s rate is a temporary solution.
=> Address problem that ES disk fills to quickly in normal benchmarks.

charts/zeebe-benchmark/README.md, charts/zeebe-benchmark/templates/NOTES.txt, charts/zeebe-benchmark/templates/benchmark-config.yaml, charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/test/zeebe_config_test.go, charts/zeebe-benchmark/values-realistic-benchmark.yaml, charts/zeebe-benchmark/values.yaml
Our pyroscope setup was not working correctly anyway so let's remove support for it. This helps speed up installation a bit because we no longer need the init container that downloads pyroscope.
=> fix: remove broken profiling support

charts/zeebe-benchmark/test/golden/c8-core-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
Restore the truncation of the names for the Elasticsearch service in the benchmark config.
closes #232
related to https://github.com/camunda/zeebe-benchmark-helm/pull/143
=> fix: truncate es name

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/values.yaml
The archiver property was renamed to `history` and the enabled flag was removed
relates to https://github.com/camunda/camunda/issues/29386
=> refactor: renamed archiver to history for camunda exporter settings

charts/zeebe-benchmark/test/golden/c8-core-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
The retention configurations got changed. These are now under `core.history.retention`. I've changed them here accordingly.
See: https://github.com/camunda/camunda/blob/5bf070046d38e0f234335111fdcca6c2aaea593d/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/config/ExporterConfiguration.java#L19
and: https://github.com/camunda/camunda-platform-helm/pull/3169
closes #235
=> Configure retention for exporters

charts/zeebe-benchmark/Chart.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml
Finally a stable alpha version of 8.8 got released 🎉 I have upgraded the camunda platform chart to 13.0.0-alpha2. Note that I had to also change the repository, as alpha charts are now published on the helm repo used by our customers.
closes #234
=> Move to a stable camunda-platform version

charts/zeebe-benchmark/README.md
Recently there were requests from other teams not familiar with the repo to explain how to run the benchmarks against saas, and there were no resources to point to. We should have a short explanation in the read.me on how to perform this and to inform readers that this is possible.
This PR adds these steps and explains how to adjust PI creation rate in the starter.
closed: https://github.com/camunda/zeebe-benchmark-helm/issues/243
=> Add short description on how to run the benchmark against saas.

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-starter.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-starter.golden.yaml, charts/zeebe-benchmark/test/golden/starter-extended.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/values.yaml
Due to the benchmarks being down recently due to slow exporting which is caused by slow archiving, we want to prioritise maintaining the weekly benchmarks before this issue is fixed. 
This PR reduces the starter rate to 50 (from 150), sets in the exporter `rolloverBatchSize` to 300, and the `numberOfShards` in operate to 3.
For more details: https://camunda.slack.com/archives/C08D74J6HUG/p1740757986906249?thread_ts=1740412731.557659&cid=C08D74J6HUG
=> Reduce load in starter and change default configs to reduce slow Archiver impact

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/values.yaml
* Schema management has been moved out of exporter - to be bootstrap at start; once
* With that also retention and ILM policy creation has been moved
=> fix: set retention in camunda.database

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
Enable NMT in  "lightweight" mode  with ` -XX:NativeMemoryTracking=summary` and camunda's new jfr metrics to expose the native memory tracking metrics in prometheus.
Flag was introduced in camunda/camunda#31018
=> feat: add NMT and enable camunda custom jfr metrics

charts/zeebe-benchmark/test/golden/golden-credentials-starter.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-starter.golden.yaml, charts/zeebe-benchmark/test/golden/starter-extended.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/values.yaml
We were able to show that our current main can withstand a higher load again (of 150 PIs, back to normal). This allows us to bring back the default of the starters.
=> Increase normal benchmark default load

charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
Due [to recent refactorings and changes](https://github.com/camunda/zeebe-benchmark-helm/pull/213/files#diff-6d8e2ff7ac2a07b94bd219e3231be93610964969ffb473f0135a96f7b8f8cddf) we lost some important configurations related to the storage class and node selector.
**This PR sets:**
* The storage class again to SSD, as per default HDD are used and have unreliable latency and cause performance regressions https://github.com/camunda/camunda/issues/31702
* Sets the node selector to small nodes, to make sure we run on a single node (1-1 mapping). Avoids the noisy neighbor syndrom
* Correctly sets the elasticsearch minimal disruption budget, so we make sure there are always 2 nodes available (we had this before as well)
closes https://github.com/camunda/camunda/issues/31702
**Benchmarks**
I [have …
=> Bring SSD and other settings back

charts/zeebe-benchmark/test/golden/c8-core-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
The workaround made in https://github.com/camunda/zeebe-benchmark-helm/pull/261 to skip the error
```
[camunda][error]
DEPRECATION NOTICE: Starting from appVersion 8.7, the Camunda Helm chart will no longer automatically generate passwords for the Identity component.
Users must provide passwords as Kubernetes secrets.
The following values inside your values.yaml need to be set but were not:
global.identity.auth.core.existingSecret.name
```
requires creating a secret 
```
4m53s (x857 over 3h19m)   Warning   Failed                 Pod/hb-schema-test-zeebe-2           Error: secret "to-be-removed" not found
```
With the help of @hamza-m-masood , we figured out that we can simply set the value `global.identity.auth.enabled=false`
=> fix: disable identity

.github/workflows/chart-prepare-release.yaml, Makefile, RELEASE.md
Alternative for macOS and Windows users as the `make release.chores` command does not work as expected.
The job is tested here https://github.com/camunda/zeebe-benchmark-helm/actions/runs/15569867040
=> ci: add prepare release workflow

Makefile, charts/zeebe-benchmark/templates/leader-balancing-cron.yaml, charts/zeebe-benchmark/templates/starter.yaml, charts/zeebe-benchmark/templates/workers.yaml, charts/zeebe-benchmark/test/golden/c8-core-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-service.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/test/golden/golden-credentials-workers.golden.yaml, charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-workers.golden.yaml, charts/zeebe-benchmark/test/golden/leader-balancing-cron.golden.yaml, charts/zeebe-benchmark/test/golden/starter-extended.golden.yaml, charts/zeebe-benchmark/test/golden/starter.golden.yaml, charts/zeebe-benchmark/test/golden/workers.golden.yaml, charts/zeebe-benchmark/values.yaml
During my performance investigation I stumbled over some things, which I collected in this PR
* Change worker pod names from `benchmark-worker` to just `worker`
* Change service name of core statefulset to `camunda` allows to simplify connection strings
* Also good step forward to decouple Camunda Platform chart from Benchmark apps chart \cc @npepinpe 
* Add a makefile goal to easily delete PVCs - as helm uninstall not removes them
=> Smaller life-enriching measures

charts/zeebe-benchmark/test/golden/benchmark-config.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-configmap.golden.yaml, charts/zeebe-benchmark/test/golden/c8-core-statefulset.golden.yaml, charts/zeebe-benchmark/values.yaml
As raised in https://camunda.slack.com/archives/C09EECUGCER, when the retentition is 0s we endup recreating the index since the archiving lasts longer, which then causes that these indexes dont get cleaned after.
=> Change retentition to 70m instead of 1s
