charts/zeebe-benchmark/templates/leader-balancing-cron.yaml
charts/zeebe-benchmark/values.yaml

Add a new cron job for regularly rebalance cluster leadership, this can disabled via values file.

Leader balancing cronjob

---

charts/zeebe-benchmark/values.yaml

feat: use `zeebe.config` to configure gateway too

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.7

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.8

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.9

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.10

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.11

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.12

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.13

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.15

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.16

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.17

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.18

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.19

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.20

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.21

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.1.22

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.2.1

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.2.2

---

Makefile
charts/zeebe-benchmark/templates/NOTES.txt

* Add more details like, what image is used and
whether Operate was enabled, etc.
* For testing helm chart, via makefile, print the subchart notes
to see more details on configuration

Improve chart release notes

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.2.3

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.2.4

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.2

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.4

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.5

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.6

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.8

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Reverts camunda/zeebe-benchmark-helm#238

Revert "Release Zeebe Benchmark Helm Chart v0.3.11"

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.11

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.12

---

charts/zeebe-benchmark/Chart.yaml

Release Zeebe Benchmark Helm Chart v0.3.13

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.14

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.15

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.18

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.19

---

charts/zeebe-benchmark/templates/starter.yaml
charts/zeebe-benchmark/templates/workers.yaml
charts/zeebe-benchmark/test/golden/golden-credentials-starter.golden.yaml
charts/zeebe-benchmark/test/golden/golden-credentials-workers.golden.yaml
charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-starter.golden.yaml
charts/zeebe-benchmark/test/golden/golden-existing-credential-secret-workers.golden.yaml
charts/zeebe-benchmark/test/golden/starter-extended.golden.yaml
charts/zeebe-benchmark/test/golden/starter.golden.yaml
charts/zeebe-benchmark/test/golden/workers.golden.yaml
charts/zeebe-benchmark/values.yaml

* Make it possible to enable the REST usage for the starter and workers

Make it possible to enable REST API usage

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.20

---

charts/zeebe-benchmark/Chart-with-artifacthub-changes.yaml.tmp
charts/zeebe-benchmark/Chart.yaml
charts/zeebe-benchmark/RELEASE-NOTES.md

Release Zeebe Benchmark Helm Chart v0.3.22
